### ISSUE TITLE
align interface for file formats containing multiple tables

### ISSUE THREAD

**Issue by lungben** [lungben/TableIO.jl#25]
Some file formats, e.g. xlsx, sqlite, hdf, allow storage of multiple tables inside one file.
Currently, the interfaces for these file formats are inconsistent.

Proposed common api:

Define 2 methods for `read_table`: one method with table name and one without. 
For the latter, return the content of the alphabetically first table, but log a warning if the file contains more than one table.

For `write_table!`, the table name should always be given, no "default" table name is used.
For zipped files, giving the filename inside the zip archive should stay optional, if it is not given, the data is stored in csv format with filename equal to the archive name.

**Comment by pankgeorg** [comment]
That's great I think.
The only 'issue' I see is that the warning won't be visible to pluto users (but that's a Pluto issue!)

**Comment by lungben** [comment]
fixed in 175a12394d743d302ac53cb0b38bdafbcbe08d29
