### ISSUE TITLE
Referencing Table Inside a Schema

### ISSUE THREAD

**Issue by mrufsvold** [lungben/TableIO.jl#30]
I'm working with a database that has multiple schemas. I'd like to get a DataFrame from the table "Reference"."Date". 

When I run `list_tables(conn)`, I get "Date" in the list of tables, but when I run, `read_table(conn, "Date")`, it errors because there is no such table. And when I try "Reference.Date" or "\"Reference\".\"Date\"", I get an error because table_name can only have alphanumeric characters (I think it is erroring on the period). 

I'm relatively new to Julia and TableIO, so I'm sure I'm just missing something. I'd appreciate any help getting a solution for this.

**Comment by lungben** [comment]
Thanks for reporting!

There is an explicit check for valid characters in table names, now it also allows dots. 
Please let me know if your issue persists in the new version which will be released shortly.

**Comment by mrufsvold** [comment]
Thanks for working on this!
